version: '3'
services:
  mongo-db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017

  springboot-app:
    #image: springboot-docker:0.0.1-SNAPSHOT
    build: 
      context: . #Dockerfileを指定（カレント）
      args: #Dockerfileの引数を指定
        - JAR_FILE=./build/libs/spring-boot_with_docker-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
    depends_on:
      - mongo-db