version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017

  springboot-app:
    image: springboot-docker:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - mongodb